/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DcElectionCandidate {
        "bio": string;
        "fullname": string;
        "office": string;
        "photo": string;
    }
    interface DcElectionGallery {
        "filename": string;
    }
    interface DcElectionQuestion {
        /**
          * Holds an Array of answers to candidates [    {response: "Yes", "candidates": ["C1", "C2"]},    {response: "No", "candidates": ["C3", "C4"]}  ]
         */
        "groups": Array<any>;
        "question": string;
    }
}
declare global {
    interface HTMLDcElectionCandidateElement extends Components.DcElectionCandidate, HTMLStencilElement {
    }
    var HTMLDcElectionCandidateElement: {
        prototype: HTMLDcElectionCandidateElement;
        new (): HTMLDcElectionCandidateElement;
    };
    interface HTMLDcElectionGalleryElement extends Components.DcElectionGallery, HTMLStencilElement {
    }
    var HTMLDcElectionGalleryElement: {
        prototype: HTMLDcElectionGalleryElement;
        new (): HTMLDcElectionGalleryElement;
    };
    interface HTMLDcElectionQuestionElement extends Components.DcElectionQuestion, HTMLStencilElement {
    }
    var HTMLDcElectionQuestionElement: {
        prototype: HTMLDcElectionQuestionElement;
        new (): HTMLDcElectionQuestionElement;
    };
    interface HTMLElementTagNameMap {
        "dc-election-candidate": HTMLDcElectionCandidateElement;
        "dc-election-gallery": HTMLDcElectionGalleryElement;
        "dc-election-question": HTMLDcElectionQuestionElement;
    }
}
declare namespace LocalJSX {
    interface DcElectionCandidate {
        "bio"?: string;
        "fullname"?: string;
        "office"?: string;
        "photo"?: string;
    }
    interface DcElectionGallery {
        "filename"?: string;
    }
    interface DcElectionQuestion {
        /**
          * Holds an Array of answers to candidates [    {response: "Yes", "candidates": ["C1", "C2"]},    {response: "No", "candidates": ["C3", "C4"]}  ]
         */
        "groups"?: Array<any>;
        "question"?: string;
    }
    interface IntrinsicElements {
        "dc-election-candidate": DcElectionCandidate;
        "dc-election-gallery": DcElectionGallery;
        "dc-election-question": DcElectionQuestion;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dc-election-candidate": LocalJSX.DcElectionCandidate & JSXBase.HTMLAttributes<HTMLDcElectionCandidateElement>;
            "dc-election-gallery": LocalJSX.DcElectionGallery & JSXBase.HTMLAttributes<HTMLDcElectionGalleryElement>;
            "dc-election-question": LocalJSX.DcElectionQuestion & JSXBase.HTMLAttributes<HTMLDcElectionQuestionElement>;
        }
    }
}
